name: 'bsky-image-bot Post Next Image'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
on:
  # Comment out workflow_dispatch and uncomment the schedule to run daily
  # workflow_dispatch:
   schedule:
    - cron: "2 * * * *"

jobs:
  # On some job, do some stuff and persist variables meant to be re-used in other jobs
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        
  post-next-image:
    name: Post Next Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Do the post
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          LAST_IMAGE_NAME: ${{ vars.LAST_IMAGE_NAME }}
        run: |
          echo "Previous image name: $LAST_IMAGE_NAME"
          echo "Authenticating with user identifier: $BSKY_IDENTIFIER"
          NEW_LAST_IMAGE_NAME=$(yarn --silent run start)
          echo "NEW_LAST_IMAGE_NAME=$NEW_LAST_IMAGE_NAME" >> $GITHUB_ENV

      - uses: action-pack/set-variable@v1
        with:
          name: 'LAST_IMAGE_NAME'
          value: ${{ env.NEW_LAST_IMAGE_NAME }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
